### ISSUE TITLE
FFI\Exception : Failed loading 'libvips.so.42' after upgrade to v2

### ISSUE THREAD

**Issue by boris-glumpler** [libvips/php-vips#140] opened 2022-03-28 12:17 UTC
Hello,

I've just upgraded a PHP 8.1 app from v1 to v2 and am now getting the following exception:

```
FFI\Exception : Failed loading 'libvips.so.42'
.../vendor/jcupitt/vips/src/Config.php:310
.../vendor/jcupitt/vips/src/Config.php:195
.../vendor/jcupitt/vips/src/Config.php:259
.../vendor/jcupitt/vips/src/Image.php:712
```

I've enabled FFI like so:

```
FFI support => enabled

Directive => Local Value => Master Value
ffi.enable => On => On
ffi.preload => no value => no value
```

I also removed the vips php extension, libvips is on version `8.12.2` and was installed via Homebrew.

I'd appreciate any pointers when you find some time. Thanks!

**Comment by boris-glumpler** [comment] 2022-03-28 13:11
Thanks for your answer. I tried a bunch of different values, but nothing seemed to work. Here's  an example:

```
export DYLD_LIBRARY_PATH="/usr/local/opt:$DYLD_LIBRARY_PATH"
```

Do you know which path I should add here?

**Comment by jcupitt** [comment] 2022-03-28 14:24
It need to include the directory with the libvips.dylib shared library in, so find that and check the dir is in there.

**Comment by boris-glumpler** [comment] 2022-03-28 14:51
Found the directory `/usr/local/Cellar/vips/8.12.2_1/lib`, added it to `DYLD_LIBRARY_PATH ` but am still getting the same exception.

**Comment by andrefelipe** [comment] 2022-03-28 16:46
Have the same issue here `Failed loading 'libvips.so.42'`

On newer macOS the path is `/opt/homebrew/lib` but still doesn't work. Also tried setting the real folder too, in my case `/opt/homebrew/Cellar/vips/8.12.2_1/lib`.

Also using DYLD_FALLBACK_LIBRARY_PATH which I saw somewhere on internet but no good too:
`export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib`

Looking forward to have it working. Thank you so much for your time.

**Comment by andrefelipe** [comment] 2022-03-28 16:55
Found it!!!

PHP_OS_FAMILY constant is "Darwin" in my case (not sure about "OSX")

So at "Config.php" file I changed the libraryName function to be:
```
private static function libraryName($name, $abi)
    {
        switch (PHP_OS_FAMILY) {
            case "Windows":
                return "$name-$abi.dll";

            case "OSX":
            case "Darwin":
                return "$name.$abi.dylib";

            default:
                // most *nix
                return "$name.so.$abi";
        }
    }
```

**Comment by andrefelipe** [comment] 2022-03-28 16:59
Also found that DYLD_LIBRARY_PATH is not needed. I removed it and restarted my machine, everything is working. 

By the way, thanks @jcupitt for this new solution to load the lib directly! I been having trouble with PECL for too long now.

**Comment by jcupitt** [comment] 2022-03-28 17:08
OK, released as 2.0.1, thanks again for finding this stupidity.

**Comment by andrefelipe** [comment] 2022-03-28 17:08
Thanks again @jcupitt have a good week!

Libvips is awesome, have relying on it for years, and happy I do.

**Comment by boris-glumpler** [comment] 2022-03-28 17:15
Cheers @jcupitt!

**Closed** 2022-03-28 17:58 UTC

**Comment by pdrhlik** [comment] 2022-05-07 14:55
Hi @jcupitt,

I've just found out about libvips and wanted to give it a try because imagick is constantly giving me pain. I stumbled upon the same error as in this issue but I haven't been able to resolve it. I'm trying to run it on MacOS 12.3.1.

I've followed the installation instructions on the main page but I still keep getting `Failed loading 'libvips.42.dylib' `. I've tried setting `DYLD_LIBRARY_PATH `, installing vips pecl extension but I still keep getting this error. I found the library and it is indeed installed in the right place. The program died exactly where your FIXME comment is:

```
FIXME ... maybe display a helpful message on failure? This will
probably be the main point of failure.
```

Do you have any ideas or suggestions? Thanks a lot. I'd really love to try this library out.

Cheers,
Patrik

**Comment by jcupitt** [comment] 2022-05-07 15:08
Hi @pdrhlik,

I guess this is with homebrew, and the lib is in `/opt/homebrew/lib`, is that right? Probably you just need to log out and in again so that the paths are all updated.

**Comment by pdrhlik** [comment] 2022-05-07 15:12
It is in `/opt/homebrew/Cellar/vips/8.12.2_2/lib` and linked to `/opt/homebrew/lib`. I tried restarting the computer but that didn't help. Could you think of something else?

**Comment by jcupitt** [comment] 2022-05-07 15:35
Homebrew keep changing the way they handle this, and M1 macs are different again :/ I have an old intel mac for testing, but I can't get to it right now.

I would try setting the library path:

```
export DYLD_LIBRARY_PATH=/opt/homebrew/lib
```

You don't need the PECL extension for php-vips 2.0+, so I'd remove that.

**Comment by pdrhlik** [comment] 2022-05-07 15:48
Tried removing the PECL extension and setting `DYLD_LIBRARY_PATH` but no luck. I happen to have an M1 mac so it might be the issue? My production system will be Ubuntu but I wanted to try running it on my local machine without using Docker.

So I guess bad luck for me at the moment?

**Comment by jcupitt** [comment] 2022-05-07 16:53
It should work, we're just missing some small thing.

1. How are you testing php-vips? Are you running it inside a webserver, or at the command-line? If you are trying at the command-line (see the `examples/` dir in php-vips), then just setting the lib path in your shell is fine. If you are running it from a webserver, you will need to make sure the server has that env var set when it starts.
2. Have you enabled FFI in your `php.ini`? Depending on how your php binary was installed (is it the homebrew one?) it might or might not have FFI enabled by default. 
3. I guess you have php 7.4+?

**Comment by pdrhlik** [comment] 2022-05-07 17:11
Thanks a lot for your patience, @jcupitt.

1. This might probably be the issue. I'm running it inside a webserver. I'm using caddy and I didn't I'd need to run it with such specific env vars. I'll have a look at that. I haven't encountered any need for such thing before.
2. Yes, I did enable it in `php.ini`. I double checked through `phpinfo()`.
3. I'm running php 8.1 right now.

I'll try figuring out the first thing.

**Comment by jcupitt** [comment] 2022-05-07 17:40
Ah, yes, that sounds like it. php-vips has no idea you're using homebrew, so it can't find the library because homebrew doesn't put it in a standard location. You'll need to hint the directory somehow (the lib path is probably the simplest way to do this).

**Comment by pdrhlik** [comment] 2022-05-08 16:45
Thanks for the answer. I still haven't managed to figure it out. I tried setting the env variables `DYLD_LIBRARY_PATH` and `LD_LIBRARY_PATH` to include the homebrew library path but no luck again. I also tried changing `include_path` param in `php.ini` and during runtime using `set_include_path()` but nothing worked.

The last thing to try would be to move or symlink the `libvips.42.dylib` to the location where `php-vips` is looking for it. What exact place would that be?

Thanks for your help.

**Comment by jszobody** [comment] 2022-10-07 03:07
I'm with @pdrhlik, can't get this to work at all. On php8.1, FFI enabled. No amount of tinkering with `DYLD_LIBRARY_PATH ` or `LD_LIBRARY_PATH` works for me, and I can't figure out where to symlink it so it is automatically found. However, I did find that if I hack the `Config.php` file directly and set the library to an absolute path of `/opt/homebrew/lib/libvips.42.dylib` it works! 

This leads me to wonder @jcupitt if you'd consider a PR to allow me to set an absolute library path, manually? Something like `Config::setLibPath('/opt/homebrew/lib')`. This would solve all my issues, as I already confirmed that the absolute path gets this working on all our macs.

**Comment by jcupitt** [comment] 2022-10-07 11:40
Hello @jszobody, sure a PR sounds like a good idea. I can't test on M1s so someone else will need to take the lead on this.

This seems to mostly be an issue with homebrew and the M1, so perhaps we could do this automatically? I had a quick hack:

```diff
diff --git a/examples/sig.php b/examples/sig.php
index 426890d..dfb2aef 100755
--- a/examples/sig.php
+++ b/examples/sig.php
@@ -5,6 +5,8 @@ require __DIR__ . '/../vendor/autoload.php';
 
 use Jcupitt\Vips;
 
+Vips\Config::setLogger(new Vips\DebugLogger());
+
 /**
  * sigmoidal contrast adjustment in php-vips
  *
diff --git a/src/Config.php b/src/Config.php
index 629915b..6ab4236 100644
--- a/src/Config.php
+++ b/src/Config.php
@@ -300,14 +300,38 @@ class Config
 
         Utils::debugLog("init", ["library" => $vips_libname]);
 
-        /* FIXME ... maybe display a helpful message on failure? This will
-         * probably be the main point of failure.
-         */
-        $vips = \FFI::cdef(<<<EOS
-            int vips_init (const char *argv0);
-            const char *vips_error_buffer (void);
-            int vips_version(int flag);
-            EOS, $vips_libname);
+        // attempt to open libraries using the system library search method
+        // (no prefix) and a couple of fallback paths
+        $libraryLocations = [
+            "",                         # system library
+            "/opt/homebrew/lib/",       # homebrew on M1
+            "/usr/local/lib/",          # more usual local build
+        ];
+
+        $vips = null;
+        $exception = null;
+        foreach ($libraryLocations as $base_path) {
+            Utils::debugLog("base", ["base_path" => $base_path]);
+            try {
+                $vips = \FFI::cdef(<<<EOS
+                    int vips_init (const char *argv0);
+                    const char *vips_error_buffer (void);
+                    int vips_version(int flag);
+                    EOS, "$base_path$vips_libname");
+                break;
+            } catch (\FFI\Exception $e) {
+                Utils::debugLog("library load failed", ["exception" => $e]);
+                $exception = $e;
+            }
+        }
+
+        if ($vips == null) {
+            $locations = implode(", ", $libraryLocations);
+            throw new Exception("Unable to start libvips in any of " .
+                "system-path$locations. Check that you have installed " .
+                "libvips, and that the library location is on your system " .
+                "library search path.");
+        }
 
         $result = $vips->vips_init("");
         if ($result != 0) {
@@ -776,9 +800,12 @@ EOS;
         }
 
         Utils::debugLog("init", ["binding ..."]);
-        self::$glib = \FFI::cdef($glib_decls, $glib_libname);
-        self::$gobject = \FFI::cdef($gobject_decls, $gobject_libname);
-        self::$vips = \FFI::cdef($vips_decls, $vips_libname);
+        self::$glib = \FFI::cdef($glib_decls, 
+            "$base_path$glib_libname");
+        self::$gobject = \FFI::cdef($gobject_decls, 
+            "$base_path$gobject_libname");
+        self::$vips = \FFI::cdef($vips_decls, 
+            "$base_path$vips_libname");
 
         # Useful for debugging
         # self::$vips->vips_leak_set(1);
```

And it seems to work for me. Does that fix M1?

**Comment by jcupitt** [comment] 2022-10-11 08:47
php-vips 2.1 is out now and includes a version of the patch above. Hopefully this will fix this issue.

**Comment by Toflar** [comment] 2023-07-26 18:00
In case other people are having issues with the current version `2.1.1` and Homebrew throwing `[FFI\Exception] Failed loading 'libvips.42.dylib'` on `FFI.php:735`: I didn't quite understand all of the related discussion in [Homebrew](https://github.com/Homebrew/brew/issues/13481) but it seems like for some reason, the Homebrew library is not searched automatically and they also cannot add it.

But when I `export DYLD_LIBRARY_PATH=$(brew --prefix)/lib:$DYLD_LIBRARY_PATH`, I could get this project to work 😊 Not entirely sure if all of it will work but so far, it does.

Maybe anyone else who's more familiar with the internals can understand more and even think of a way how this could be automated.  😅

**Comment by jcupitt** [comment] 2023-07-26 19:41
It should just work with current php-vips. I bought an M2 mac mini and pasted some extra code in. With homebrew libvips, no config should be necessary.

**Comment by Toflar** [comment] 2023-07-26 20:12
Did not work for me. What Homebrew version are you using? :)

**Comment by ausi** [comment] 2023-07-26 20:50
I had the same issue with version `2.1.1`, but installing the current master branch fixed it for me 
(`"jcupitt/vips": "dev-master",`)

**Comment by Toflar** [comment] 2023-07-27 06:26
Ah, it does for me too, indeed 🥳 I guess this is https://github.com/libvips/php-vips/commit/a38b72c0a131da073a9aa119c205286bf61003f6 which isn't tagged yet 😊

**Comment by zhangjiayin** [comment] 2025-01-14 05:28
add VMOPTIONS like below Maybe help to you
 --enable-native-access=ALL-UNNAMED
-Dvipsffm.libpath.vips.override=/opt/homebrew/opt/libvips/lib/libvips.dylib
-Dvipsffm.libpath.glib.override=//opt/homebrew/opt/glib/lib/libglib-2.0.0.dylib
-Dvipsffm.libpath.gobject.override=//opt/homebrew/opt/glib/lib/libgobject-2.0.0.dylib
