### ISSUE TITLE
SEGFAULT after the inclusion of FFI::shutdown() to release memory consumption

### ISSUE THREAD

**Issue by craig410** [libvips/php-vips#170] opened 2022-11-11 12:30 UTC
Running libvips 8.13.3 on Debian bullseye with PHP 8.1 under Apache using `jcupitt/vips:2.10`

Calling `FFI::shutdown()` at the end of a script after an `Image::Thumbnail()` operation results in the process SEGFAULT-ing.

The call to `shutdown()` is required as without it the memory consumption climbs and is never released back to the system (at least from our experiments).

There are more details and a full reproduction case, including Dockerfile to match the environment: https://github.com/ingenerator/libvips-segfault-repro

Thanks to @acoulton: Failing tests proving either case here: https://github.com/ingenerator/libvips-segfault-repro/actions/runs/3444654670/jobs/5747485403 

And a further attempt to debug the source of the SEGFAULT here: https://github.com/ingenerator/libvips-segfault-repro/pull/3

We have followed as much of the documentation as we can find around using`php-vips` appropriately however, it may be that it is not suited to running in this environment, in this way (ie mpm-prefork / multiuser). While happy to spend a little more time debugging, if you have any suggestions of where to go next with it? It would be good to know if it is at least intended to work this way?

**Comment by jcupitt** [comment] 2022-11-11 16:31
Hi @craig410,

I've just made a PR that (I think!) works around what is (again, I think) a bug in php-ffi. Would you be able to test it?

https://github.com/libvips/php-vips/pull/171

You shouldn't need to call shutdown, and hopefully it won't leak.

**Comment by craig410** [comment] 2022-11-11 17:32
Hi @jcupitt,

Thanks for your speedy response. We're still seeing huge memory accumulation without calling shutdown. Roughly 250% increase over 10 requests. https://github.com/ingenerator/libvips-segfault-repro/actions/runs/3446792614/jobs/5752119000

**Comment by jcupitt** [comment] 2022-11-11 18:04
Could that be the operation cache? libvips will try to cache recent operations, and has a 100mb cache limit by default.

You can change the default cache sizing here:

https://libvips.github.io/php-vips/classes/Jcupitt-Vips-Config.html#method_cacheSetMaxMem

You can also limit the cache by number of operations and number of open files.

I'd also beware of memory fragmentation. It'll take quite a few iterations (up to several 100?) before memory use stabilises.

**Comment by jcupitt** [comment] 2022-11-11 18:30
Oh sigh, this still leaks:

```
#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

#Vips\Config::setLogger(new Vips\DebugLogger());

Vips\Config::cacheSetMax(0);

if (count($argv) != 4) {
    echo("usage: ./watermark-text.php input output \"some text\"\n");
    exit(1);
}

$input_filename = $argv[1];
$output_filename = $argv[2];
$message = $argv[3];

function watermark($image, $message)
{
    $text = Vips\Image::text($message, [
      'width' => $image->width,
      'dpi' => 600,
      'rgba' => true
    ]);

    // scale the alpha down to make it semi-transparent, and rotate by 45
    // degrees
    $text = $text
        ->multiply([1, 1, 1, 0.3])
        ->rotate(45);

    // replicate and crop to match the size of the image
    $text = $text
        ->replicate(1 + $image->width / $text->width,
            1 + $image->height / $text->height)
        ->crop(0, 0, $image->width, $image->height);

    // and overlay on the image
    return $image->composite($text, "over");
}

echo "iteration, growth (bytes)\n";
$prev = 0;
for ($i = 0; $i < 2000; $i++) {
    $image = Vips\Image::newFromFile($input_filename, [
      'access' => 'sequential',
    ]);

    // no leak
    //$image = $image->invert()

    // leaks 192 bytes per loop
    $image = $image->add(1);

    // leaks 288 bytes per loop
    //$image = watermark($image, $message);

    $image->writeToFile($output_filename);

    if ($i % 10 == 0) {
        gc_collect_cycles();
        $now = memory_get_usage();
        $use = $now - $prev;
        $prev = $now;
        echo "$i, $use\n";
    }
}
```

Looks like a problem with constant handling. I'll have a further look.

**Comment by jcupitt** [comment] 2022-11-11 18:32
... let's close this issue and discuss and test in the PR.

**Comment by craig410** [comment] 2022-11-11 20:58
> Could that be the operation cache? libvips will try to cache recent operations, and has a 100mb cache limit by default.
> 
> You can change the default cache sizing here:
> 
> https://libvips.github.io/php-vips/classes/Jcupitt-Vips-Config.html#method_cacheSetMaxMem
> 
> You can also limit the cache by number of operations and number of open files.

We've already tried using a tiny cache as well as disabling it completely and noticed no appreciable difference whatsoever. I kept it out of the reproduction to keep it simple.

> 
> I'd also beware of memory fragmentation. It'll take quite a few iterations (up to several 100?) before memory use stabilises.

I've run locally 400 iterations of the same operation with the default options and memory peaked at 200MiB and settled at 198MiB

With the options 
```php
Config::cacheSetMax(0);
Config::cacheSetMaxMem(1_000_000);
Config::cacheSetMaxFiles(0);
```
memory peaked at 156MiB after ~92 iterations and remained fairly constant.

We can pick up on PR #171 assuming we're fighting the same issue

**Comment by jcupitt** [comment] 2022-11-12 11:27
Yes, let's try to a

**Comment by jcupitt** [comment] 2022-11-12 11:32
I made this test program based on your example:

```php
#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

if (count($argv) != 2) {
    echo("usage: ./thumbnail-loop.php input\n");
    exit(1);
}

function thumbnail($filename)
{   
    $image = Vips\Image::thumbnail($filename, 600, [
        'height' => 10_000_000, 
        'export-profile' => 'srgb'
    ]);

    $buf = $image->writeToBuffer('.jpg', [
        'Q' => 75, 
        'strip' => TRUE, 
        'optimize_coding' => TRUE, 
        'profile'=>'srgb'
    ]); 

    return $buf;
}

echo "iteration, growth (bytes)\n";
$prev = 0;
for ($i = 0; $i < 1000; $i++) {
    $buf = thumbnail($argv[1]);

    if ($i % 10 == 0) {
        gc_collect_cycles();
        $now = memory_get_usage();
        $use = $now - $prev;
        $prev = $now;
        echo "$i, $use\n";
    }
}
```

Running against the php-vips in that PR I see:

```
$ ./thumbnail-loop.php ~/pics/k2.jpg
iteration, growth (bytes)
0, 1138920
10, 0
20, 0
...
980, 0
990, 0
```

So no leaks in 1000 iterations, according to `memory_get_usage()`.

I'll try a version that watches RSS in `ps` instead.

**Comment by jcupitt** [comment] 2022-11-12 12:09
This seems to work OK:

```php
echo "iteration, now (kb), growth (kb)\n";
$prev = 0;
for ($i = 0; $i < 1000; $i++) {
    $buf = thumbnail($argv[1]);

    if ($i % 10 == 0) {
        gc_collect_cycles();
        $pid = getmypid();
        $now = intval(`ps --pid $$ --no-headers -orss`);
        $use = $now - $prev;
        $prev = $now;
        echo "$i, $now, $use\n";
    }
}
```

I see:

```
$ ./thumbnail-loop.php ~/pics/k2.jpg
iteration, now (kb), growth (kb)
0, 960, 960
10, 960, 0
20, 1012, 52
30, 960, -52
40, 964, 4
50, 1008, 44
60, 992, -16
...
980, 972, -40
990, 968, -4
```

So a pretty steady 1mb of RSS. I set it to 10,000 iterations and watched RES in `top`. The php process stabilised at 140mb or so in a few 10s of iterations, and crept up to 150 by 1000. It was still c. 150 at 10,000 iterations.

**Comment by jcupitt** [comment] 2022-11-12 13:12
Here's 55,000 iterations:

![x](https://user-images.githubusercontent.com/580843/201475594-7ea44b41-5532-4c42-bcfc-0ad01bfd38b4.png)

So I think it's fragmentaion and there's no leak.

**Comment by jcupitt** [comment] 2022-11-14 17:09
Hello @acoulton,

Ooof, I'm a bit vague on the details, but my understanding is that php does two types of memory allocation: per request (via emalloc) and persistent (via the system malloc).

Per request memory allocated via emalloc is automatically released at the end of a request when the request thread exits, and because it's allocated and freed in a huge chunk, can't get fragmented. Persistent objects on the other hand exist for the lifetime of the php process and are shared between threads. You can get fragmentation here, since the memory isn't pooled. 

The php side of php-vips will mostly use emalloc, so that's all fine, but the native libvips binary will of course be using the system malloc, so it'll operate like php's persistent memory. If you call `shutDown` it'll free all the libvips memory for the whole process, so yes, it'll trigger segvs.

Looking at your graph, I think it's operating as expected. You're seeing an extra 100mb, typically, cased by having a native library doing significant amounts of malloc() in your webserver process. I don't think you're seeing a leak (ie. libvips is not losing memory).

As to what you should do I suppose the choices are:

1. Leave it like this. Is the extra 100mb an issue? If not, I'd be inclined to leave it. libvips ought to be significantly faster than ext-imagick (maybe [a factor of 6 on this benchmark](https://github.com/libvips/libvips/wiki/Speed-and-memory-use)) so you could possible use a lower powered server and see a saving.
2. Move image processing to a separate process. If there's significant image processing, it's probably not a good idea to do it in your main server process. I've put processing into a separate worker process which takes jobs from a jobs table in the DB and does the processing asynchronously. Keeping heavy processing off your main server can be a good idea.
3. You could fork `vipsthumbnail`. This is super easy and will give pretty good performance.

@kleisauke could I ping you on this (sorry)? You know a lot more about this than me!

**Comment by jcupitt** [comment] 2022-11-14 17:16
Oh, as another option, libvips is fast enough that you could also resize images on demand rather than resizing on upload. 

You might see a useful drop in storage costs, and users would have images sized exactly for their device.

**Comment by kleisauke** [comment] 2022-11-14 19:24
I think this is a memory fragmentation issue. You might consider using a different memory allocator such as [jemalloc](https://github.com/jemalloc/jemalloc) to prevent memory fragmentation in long-running, multi-threaded, glibc-based Linux processes. See https://github.com/lovell/sharp/issues/955 to learn more about memory allocation and why the choice of a memory allocator is important.

You could also consider switching to a Alpine-based Docker image, as the memory allocator in musl, upon which Alpine Linux is based, is generally considered very good in terms of lack of fragmentation and returning freed memory.

For example, with these changes:
https://github.com/ingenerator/libvips-segfault-repro/compare/test-php-vips-pull-171...kleisauke:alpine-based

I see:
```
Result summary:

  - # 1 HTTP:200 Memory: 10.19MB / 33.6GB
  - # 2 HTTP:200 Memory: 15.7MB / 33.6GB
  - # 3 HTTP:200 Memory: 15.84MB / 33.6GB
  - # 4 HTTP:200 Memory: 15.96MB / 33.6GB
  - # 5 HTTP:200 Memory: 15.99MB / 33.6GB
  - # 6 HTTP:200 Memory: 16.02MB / 33.6GB
  - # 7 HTTP:200 Memory: 16.02MB / 33.6GB
  - # 8 HTTP:200 Memory: 16.05MB / 33.6GB
  - # 9 HTTP:200 Memory: 16.07MB / 33.6GB
  - # 10 HTTP:200 Memory: 16.08MB / 33.6GB
  Final Memory: 15.54MB / 33.6GB
```

So, much less memory usage than glibc.

**Comment by kleisauke** [comment] 2022-11-14 19:57
FWIW, for the same reason [Redis ships with jemalloc by default since version 2.4](http://oldblog.antirez.com/post/everything-about-redis-24.html).
> Since we introduced the specially encoded data types Redis started suffering from fragmentation. We tried different things to fix the problem, but basically the Linux default allocator in glibc sucks really, really hard. […] Every single case of fragmentation in real world systems was fixed by this change, and also the amount of memory used dropped a bit.

I'm also aware that sharp reduces the default concurrency to 1 when glibc' memory allocator is used, see commit: https://github.com/lovell/sharp/commit/5a9cc835b33001c805a0d5fcb05e6d71135cc79d

**Comment by acoulton** [comment] 2022-11-14 22:12
@jcupitt @kleisauke thank you both very much for your comments, that's extremely helpful.

I'm not hugely familiar with the details of low-level memory allocation but the malloc / emalloc explanation makes sense to me.

I think in the short term we'll explore jemalloc (@craig410 is much hotter on things like that than me so can take a look when he's back at work). And/or we may just perform image operations in a shell process as we work towards a more permanent solution.

Just to respond to a couple of your comments:

> If you call shutDown it'll free all the libvips memory for the whole process, so yes, it'll trigger segvs.

Is there any usecase where `FFI::shutDown()` is expected/valid to be called? It might be useful to others in future if there was a bit more information / a warning on the phpdoc for that method to clarify expected behaviour.  I could put together a PR with that and a couple of other possible additions to documentation with what we've learned from this process.

> 1. Leave it like this. Is the extra 100mb an issue?

Unfortunately, yes. We are running multiple container-based projects & workloads under kubernetes, and have multiple instances of every service to allow for rolling upgrades / geo-redundancy etc. That has a lot of benefits to us over traditional vhost-based shared servers, but in this specific instance is probably worse because each separate set of apache/mod_php processes will have its own malloc-blocks.

We obviously have memory headroom for spikes, but permanently increasing the baseline memory for every pod to allow for unused but fragmented space would require more / bigger nodes and have a noticeable cost implication on our cluster.

> 2. Move image processing to a separate process.

Medium-term our plan is to do just that, but there are some architectural complications with our existing codebases that make that a reasonable job in its own right. And image processing is a relatively small component of the overall workload, which hasn't traditionally taxed resources.

That said, we'd be looking to move processing either to a standalone k8s service or something like Cloud Run, so again there are cost implications to the size of permanent background memory allocation sitting idle.

> libvips is fast enough that you could also resize images on demand rather than resizing on upload.

The project we've migrated so far accepts files - mostly photos - for a single internal use. We resize on upload to the specific (quite low-res) version the system needs and only store that, discarding the much larger original images that users tend to upload.

The next project we plan to upgrade does already resize on demand with imagick, albeit behind a CDN & caching filesystem. However we'll probably keep the cache - in our architecture the source files are stored in cloud storage, as appservers are clustered & transient. So there's a cost & latency implication for pulling the originals down before any image operations even begin.

In any case I think resizing on demand would produce more image operations rather than fewer, so would make the memory fragmentation issue worse.

> consider switching to a Alpine-based Docker image

This, and migrating to php-fpm, is definitely already on our list to explore and it's really helpful to know that might also help with the fragmentation.

**Comment by jcupitt** [comment] 2022-11-14 22:20
> Is there any usecase where FFI::shutDown() is expected/valid to be called?

It also does things like checking for leaks and writing internal profiling information. It's useful if you don't plan to use libvips again in that process, or if you are trying to track down leaks or unexpected memory use (ironically).

**Comment by kleisauke** [comment] 2022-11-15 21:49
> In any case I think resizing on demand would produce more image operations rather than fewer, so would make the memory fragmentation issue worse.

FWIW, the [`weserv/images`](https://github.com/weserv/images) project uses libvips extensively and we never had problems with memory fragmentation after we migrated our servers to use jemalloc as the default memory allocator. 

We were using php-vips 1.x in production around 2017 and decided to migrate to the OpenResty / LuaJIT / lua-vips combo because PHP didn't had a JIT compiler and integrated FFI functionality at that time. Nowadays, the codebase includes an nginx module around libvips, written in C++.

**Closed** 2023-06-29 23:39 UTC

**Comment by jcupitt** [comment] 2023-12-14 15:32
Hi @DiamondMax,

> Using php-vips 1.0.10

I would use php-vips 2.3 (current stable).

**Comment by Epskampie** [comment] 2023-12-18 19:42
I'm seeing the same issue. Using `php-vips v2.3.0` on `ubuntu 23.10` which has `libvips 8.14.3-1` using apache2 with `mod_php`, all running inside docker. 

After around 100 requests with resize operations, every apache thread takes around `1.2GB` of virtual memory (checked using `htop`). I also checked using `docker stats`, which shows the container taking around 1.8GB:

```
CONTAINER ID   NAME       CPU %     MEM USAGE / LIMIT    MEM %     NET I/O           BLOCK I/O         PIDS
845bf1a5dfdf   v4-dev-1   2.00%     1.769GiB / 23.4GiB   7.56%     2.62MB / 31.2MB   35.5MB / 1.19GB   14
```
Perhaps this is all expected, or I'm doing something wrong, but it's quite surprising as this library is marketed as using little memory, but it seems this isn't actually true in its default configuration when used from PHP in a web-server environment.

**Comment by acoulton** [comment] 2023-12-20 10:39
FWIW, we never resolved this under apache & mod_php - switching the default system allocator to jemalloc made things worse (presumably due to other aspects of apache / php memory management) and we didn't find a way to use jemalloc just for libvips in this scenario.

Instead, our PHP code in the web process now uses symfony/process to shell out to a standalone PHP script that performs a single set of image transformations then exits. This does create a small overhead due to starting the processes, and having to write & read images to local disk instead of working with them in memory. But the overall memory management works "out of the box" and for our usecase where image requests make up a small % of the total, and latency is a secondary concern to ongoing memory allocation, it works well for us for now. It also saves having to enable php FFI in the apache/web process which is obviously also more secure.

We are also gradually moving image operations off to  Cloud Run, but at the moment still using the same approach so that we can reuse our existing apache-based base image. In due course we'll probably revisit that to look using VIPS through php-fpm or possibly even a different language binding.
